// Generated by Wrangler by running `wrangler types`

interface Env {
	BASE_URL: string;
	API_KEY: string;
	WORKSPACE_ID: string;
	SURVEY_ID: string;
	PAYLOAD_CONTENT_FIELD: string;
	LANGUAGE: string;
	FOCUS_CATEGORY: string;
	FEISHU_WEBHOOK: string;
	FEISHU_APP_ID: string;
	FEISHU_APP_SECRET: string;
	FEISHU_TABLE_APPTOKEN: string;
	FEISHU_TABLE_ID: string;
}
