// This file is auto-generated by @hey-api/openapi-ts

export type $OpenApiTs = {
    '/global/config': {
        get: {
            res: {
                /**
                 * Successful response
                 */
                200: {
                    allowRegister: boolean;
                    websiteId?: string;
                    amapToken?: string;
                    mapboxToken?: string;
                    alphaMode: boolean;
                    disableAnonymousTelemetry: boolean;
                    customTrackerScriptName?: string;
                };
            };
        };
    };
    '/login': {
        post: {
            req: {
                requestBody: {
                    username: string;
                    password: string;
                };
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    info: {
                        username: string;
                        id: string;
                        role: string;
                        createdAt: string;
                        updatedAt: string;
                        deletedAt: string | null;
                        currentWorkspace: {
                            id: string;
                            name: string;
                            dashboardLayout: {
                                layouts: {
                                    [key: string]: (unknown[]);
                                };
                                items: unknown[];
                            } | null;
                        };
                        workspaces: Array<{
                            role: string;
                            workspace: {
                                id: string;
                                name: string;
                            };
                        }>;
                    };
                    token: string;
                };
            };
        };
    };
    '/loginWithToken': {
        post: {
            req: {
                requestBody: {
                    token: string;
                };
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    info: {
                        username: string;
                        id: string;
                        role: string;
                        createdAt: string;
                        updatedAt: string;
                        deletedAt: string | null;
                        currentWorkspace: {
                            id: string;
                            name: string;
                            dashboardLayout: {
                                layouts: {
                                    [key: string]: (unknown[]);
                                };
                                items: unknown[];
                            } | null;
                        };
                        workspaces: Array<{
                            role: string;
                            workspace: {
                                id: string;
                                name: string;
                            };
                        }>;
                    };
                    token: string;
                };
            };
        };
    };
    '/register': {
        post: {
            req: {
                requestBody: {
                    username: string;
                    password: string;
                };
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    info: {
                        username: string;
                        id: string;
                        role: string;
                        createdAt: string;
                        updatedAt: string;
                        deletedAt: string | null;
                        currentWorkspace: {
                            id: string;
                            name: string;
                            dashboardLayout: {
                                layouts: {
                                    [key: string]: (unknown[]);
                                };
                                items: unknown[];
                            } | null;
                        };
                        workspaces: Array<{
                            role: string;
                            workspace: {
                                id: string;
                                name: string;
                            };
                        }>;
                    };
                    token: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/getServiceCount': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    website: number;
                    monitor: number;
                    server: number;
                    telemetry: number;
                    page: number;
                    survey: number;
                };
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/onlineCount': {
        get: {
            req: {
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/website/all': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    workspaceId: string;
                    name: string;
                    domain: string | null;
                    shareId: string | null;
                    resetAt: string | null;
                    monitorId: string | null;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt: string | null;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/info': {
        get: {
            req: {
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    domain: string | null;
                    shareId: string | null;
                    resetAt: string | null;
                    monitorId: string | null;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt: string | null;
                } | null;
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/stats': {
        get: {
            req: {
                browser?: string;
                city?: string;
                country?: string;
                device?: string;
                endAt: number;
                os?: string;
                referrer?: string;
                region?: string;
                startAt: number;
                timezone?: string;
                title?: string;
                unit?: string;
                url?: string;
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    pageviews: {
                        value: number;
                        prev: number;
                    };
                    uniques: {
                        value: number;
                        prev: number;
                    };
                    totaltime: {
                        value: number;
                        prev: number;
                    };
                    bounces: {
                        value: number;
                        prev: number;
                    };
                };
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/geoStats': {
        get: {
            req: {
                endAt: number;
                startAt: number;
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    longitude: number;
                    latitude: number;
                    count: number;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/pageviews': {
        get: {
            req: {
                browser?: string;
                city?: string;
                country?: string;
                device?: string;
                endAt: number;
                os?: string;
                referrer?: string;
                region?: string;
                startAt: number;
                timezone?: string;
                title?: string;
                unit?: string;
                url?: string;
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    pageviews?: unknown;
                    sessions?: unknown;
                };
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/metrics': {
        get: {
            req: {
                browser?: string;
                city?: string;
                country?: string;
                device?: string;
                endAt: number;
                event?: string;
                language?: string;
                os?: string;
                referrer?: string;
                region?: string;
                startAt: number;
                title?: string;
                type: 'url' | 'language' | 'referrer' | 'browser' | 'os' | 'device' | 'country' | 'event';
                url?: string;
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    x: string | null;
                    y: number;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/website/add': {
        post: {
            req: {
                requestBody: {
                    name: string;
                    domain: string | unknown;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    domain: string | null;
                    shareId: string | null;
                    resetAt: string | null;
                    monitorId: string | null;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt: string | null;
                };
            };
        };
    };
    '/workspace/{workspaceId}/website/{websiteId}/update': {
        put: {
            req: {
                requestBody: {
                    name: string;
                    domain: string | unknown;
                    monitorId?: string | null;
                };
                websiteId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    domain: string | null;
                    shareId: string | null;
                    resetAt: string | null;
                    monitorId: string | null;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt: string | null;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/all': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    workspaceId: string;
                    name: string;
                    type: string;
                    active: boolean;
                    interval: number;
                    maxRetries: number;
                    payload: {
                        [key: string]: unknown;
                    };
                    createdAt: string;
                    updatedAt: string;
                    notifications: Array<{
                        id: string;
                    }>;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}': {
        get: {
            req: {
                monitorId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    type: string;
                    active: boolean;
                    interval: number;
                    maxRetries: number;
                    payload: {
                        [key: string]: unknown;
                    };
                    createdAt: string;
                    updatedAt: string;
                    notifications: Array<{
                        id: string;
                    }>;
                } | null;
            };
        };
        delete: {
            req: {
                monitorId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    type: string;
                    active: boolean;
                    interval: number;
                    maxRetries: number;
                    payload: {
                        [key: string]: unknown;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/monitor/getPublicInfo': {
        post: {
            req: {
                requestBody: {
                    monitorIds: Array<(string)>;
                };
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    name: string;
                    type: string;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/upsert': {
        post: {
            req: {
                requestBody: {
                    id?: string;
                    name: string;
                    type: string;
                    active?: boolean;
                    interval?: number;
                    maxRetries?: number;
                    notificationIds?: Array<(string)>;
                    payload: {
                        [key: string]: unknown;
                    };
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    type: string;
                    active: boolean;
                    interval: number;
                    maxRetries: number;
                    payload: {
                        [key: string]: unknown;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}/data': {
        get: {
            req: {
                endAt: number;
                monitorId: string;
                startAt: number;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    value: number;
                    createdAt: string;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}/changeActive': {
        patch: {
            req: {
                monitorId: string;
                requestBody: {
                    active: boolean;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    type: string;
                    active: boolean;
                    interval: number;
                    maxRetries: number;
                    payload: {
                        [key: string]: unknown;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}/recentData': {
        get: {
            req: {
                monitorId: string;
                take: number;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    value: number;
                    createdAt: string;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}/dataMetrics': {
        get: {
            req: {
                monitorId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    recent1DayAvg: number;
                    recent1DayOnlineCount: number;
                    recent1DayOfflineCount: number;
                    recent30DayOnlineCount: number;
                    recent30DayOfflineCount: number;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/events': {
        get: {
            req: {
                limit?: number;
                monitorId?: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    message: string;
                    monitorId: string;
                    type: string;
                    createdAt: string;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/clearEvents': {
        delete: {
            req: {
                monitorId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/clearData': {
        delete: {
            req: {
                monitorId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/{monitorId}/status': {
        get: {
            req: {
                monitorId: string;
                statusName: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    monitorId: string;
                    statusName: string;
                    payload: 'null' | null | {
    [key: string]: unknown;
} | unknown[] | string | boolean | number;
                    createdAt: string;
                    updatedAt: string;
                } | null;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/getAllPages': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    workspaceId: string;
                    slug: string;
                    title: string;
                    description: string;
                    monitorList: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                    createdAt: string;
                    updatedAt: string;
                }>;
            };
        };
    };
    '/monitor/getPageInfo': {
        get: {
            req: {
                slug: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    slug: string;
                    title: string;
                    description: string;
                    monitorList: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                    createdAt: string;
                    updatedAt: string;
                } | null;
            };
        };
    };
    '/workspace/{workspaceId}/monitor/createStatusPage': {
        post: {
            req: {
                requestBody: {
                    slug: string;
                    title: string;
                    description?: string;
                    monitorList?: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    slug: string;
                    title: string;
                    description: string;
                    monitorList: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/updateStatusPage': {
        patch: {
            req: {
                requestBody: {
                    id: string;
                    slug?: string;
                    title?: string;
                    description?: string;
                    monitorList?: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    slug: string;
                    title: string;
                    description: string;
                    monitorList: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/monitor/deleteStatusPage': {
        delete: {
            req: {
                id: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    slug: string;
                    title: string;
                    description: string;
                    monitorList: Array<{
                        id: string;
                        showCurrent?: boolean;
                    }>;
                    domain?: string | null;
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/all': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    workspaceId: string;
                    name: string;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt?: string | null;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/info': {
        get: {
            req: {
                telemetryId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt?: string | null;
                } | null;
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/allEventCount': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/eventCount': {
        get: {
            req: {
                telemetryId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/upsert': {
        post: {
            req: {
                requestBody: {
                    telemetryId?: string;
                    name: string;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt?: string | null;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/delete': {
        post: {
            req: {
                requestBody: {
                    telemetryId: string;
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    createdAt: string;
                    updatedAt: string;
                    deletedAt?: string | null;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/pageviews': {
        get: {
            req: {
                city?: string;
                country?: string;
                endAt: number;
                region?: string;
                startAt: number;
                telemetryId: string;
                timezone?: string;
                unit?: string;
                url?: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    pageviews?: unknown;
                    sessions?: unknown;
                };
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/metrics': {
        get: {
            req: {
                city?: string;
                country?: string;
                endAt: number;
                region?: string;
                startAt: number;
                telemetryId: string;
                timezone?: string;
                type: 'source' | 'url' | 'event' | 'referrer' | 'country';
                url?: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    x: string | null;
                    y: number;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/telemetry/stats': {
        get: {
            req: {
                city?: string;
                country?: string;
                endAt: number;
                region?: string;
                startAt: number;
                telemetryId: string;
                timezone?: string;
                unit?: string;
                url?: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    pageviews: {
                        value: number;
                        prev: number;
                    };
                    uniques: {
                        value: number;
                        prev: number;
                    };
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//all': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: Array<{
                    id: string;
                    workspaceId: string;
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                    createdAt: string;
                    updatedAt: string;
                }>;
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}': {
        get: {
            req: {
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                    createdAt: string;
                    updatedAt: string;
                } | null;
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}/count': {
        get: {
            req: {
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//allResultCount': {
        get: {
            req: {
                workspaceId: string;
            };
            res: {
                /**
                 * Error response
                 */
                200: {
                    message: string;
                    code: string;
                    issues?: Array<{
                        message: string;
                    }>;
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}/submit': {
        post: {
            req: {
                requestBody: {
                    payload: {
                        [key: string]: unknown;
                    };
                };
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: unknown;
            };
        };
    };
    '/workspace/{workspaceId}/survey//create': {
        post: {
            req: {
                requestBody: {
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                };
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}/update': {
        patch: {
            req: {
                requestBody: {
                    name?: string;
                    payload?: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                };
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}/delete': {
        delete: {
            req: {
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    id: string;
                    workspaceId: string;
                    name: string;
                    payload: {
                        items: Array<{
                            label: string;
                            name: string;
                            type: 'text' | 'select' | 'email';
                            options?: Array<(string)>;
                        }>;
                    };
                    createdAt: string;
                    updatedAt: string;
                };
            };
        };
    };
    '/workspace/{workspaceId}/survey//{surveyId}/result/list': {
        get: {
            req: {
                cursor?: string;
                limit?: number;
                surveyId: string;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    items: Array<{
                        id: string;
                        surveyId: string;
                        createdAt: string;
                        sessionId: string;
                        payload: {
                            [key: string]: unknown;
                        };
                        browser?: string | null;
                        os?: string | null;
                        language?: string | null;
                        ip?: string | null;
                        country?: string | null;
                        subdivision1?: string | null;
                        subdivision2?: string | null;
                        city?: string | null;
                        longitude?: number | null;
                        latitude?: number | null;
                        accuracyRadius?: number | null;
                    }>;
                    nextCursor?: string;
                };
            };
        };
    };
    '/audit/fetchByCursor': {
        get: {
            req: {
                cursor?: string;
                limit?: number;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    items: Array<{
                        id: string;
                        workspaceId: string;
                        content: string;
                        relatedId?: string | null;
                        relatedType?: 'Monitor' | 'Notification' | null;
                        createdAt: string;
                    }>;
                    nextCursor?: string;
                };
            };
        };
    };
    '/billing/usage': {
        get: {
            req: {
                endAt: number;
                startAt: number;
                workspaceId: string;
            };
            res: {
                /**
                 * Successful response
                 */
                200: {
                    websiteAcceptedCount: number;
                    websiteEventCount: number;
                    monitorExecutionCount: number;
                };
            };
        };
    };
};